### ISSUE TITLE
分享一个简单的方法

### ISSUE THREAD

**Issue by amilys** [onlypeng/dsm7_login_translucent#1]
控制面板->登录门户->登录样式->页脚信息：粘贴以下css：
<style type="text/css">
.tab-panel {
 background: rgba(255,255,255,0.5) !important; 
}
 .login-textfield .input-container input {
background-color: transparent !important;
}
</style>

勾选“已HTML语法现实页脚信息”

第3行0.5 表示透明度，适合任何型号
![image](https://user-images.githubusercontent.com/11211624/193451156-a9fb9e98-02ec-462d-910c-8d6dba42f3ee.png)

**Comment by wanzhouran** [comment]
实测可以，但是整体页面亮度感觉很暗，有办法调整页面亮度么？

**Comment by onlypeng** [comment]
<style type="text/css"> .tab-panel { background: rgba(255,255,255,0.5) !important; } .login-textfield .input-container input { background-color: transparent !important; } body { -webkit-filter:brightness(1); -o-filter:brightness(1); -moz-filter:brightness(1);  filter:brightness(1);} </style>
/* 调整页面亮度，更改新加代码中数字1，1是原亮度，高调亮，低调暗 */

**Comment by wp77** [comment]
登陆框想挪到左边去怎么办？
