### ISSUE TITLE
有没有支持DSM 7.2-64561这个版本的？

### ISSUE THREAD

**Issue by Crazyboyjw** [onlypeng/dsm7_login_translucent#2]
有没有支持DSM 7.2-64561这个版本的？  谢谢

**Comment by TIMhao** [comment]
同求群晖7.2版本的

**Comment by onlypeng** [comment]
我没安装7.2，没法测试，可以尝试一下7.1.1，我在论坛好像看见有人尝试成功了

**Comment by onefox1** [comment]
7.2试了一下,log提示系统文件不存在

**Comment by youxyx** [comment]
> 我没安装7.2，没法测试，可以尝试一下7.1.1，我在论坛好像看见有人尝试成功了

不行，替换的图片名不一样，只替换css文件会显示错误。版本不同还是不大行

**Comment by onlypeng** [comment]
> > 我没安装7.2，没法测试，可以尝试一下7.1.1，我在论坛好像看见有人尝试成功了
> 
> 不行，替换的图片名不一样，只替换css文件会显示错误。版本不同还是不大行

更新了，尝试一下，我测试的是7.2.1-69057版本

**Comment by onlypeng** [comment]
> 有没有支持DSM 7.2-64561这个版本的？ 谢谢

已更新

**Comment by onlypeng** [comment]
> 同求群晖7.2版本的

已更新

**Comment by Crazyboyjw** [comment]
> > 有没有支持DSM 7.2-64561这个版本的？ 谢谢
> 
> 已更新

![image](https://github.com/onlypeng/dsm7_login_translucent/assets/51878592/be677665-2141-4b8c-a693-9ab579d51565)
7.2.1使用后  整个系统界面都变得很虚  很多按钮的底色都没了
正常的是下图的样子
![image](https://github.com/onlypeng/dsm7_login_translucent/assets/51878592/4cadb649-5271-4d3a-9acb-e35a9c92c0eb)

**Comment by onlypeng** [comment]
> > > 有没有支持DSM 7.2-64561这个版本的？ 谢谢
> > 
> > 
> > 已更新
> 
> ![image](https://user-images.githubusercontent.com/51878592/280909690-be677665-2141-4b8c-a693-9ab579d51565.png) 7.2.1使用后 整个系统界面都变得很虚 很多按钮的底色都没了 正常的是下图的样子 ![image](https://user-images.githubusercontent.com/51878592/280909988-4cadb649-5271-4d3a-9acb-e35a9c92c0eb.png)



> > > 有没有支持DSM 7.2-64561这个版本的？ 谢谢
> > 
> > 
> > 已更新
> 
> ![image](https://user-images.githubusercontent.com/51878592/280909690-be677665-2141-4b8c-a693-9ab579d51565.png) 7.2.1使用后 整个系统界面都变得很虚 很多按钮的底色都没了 正常的是下图的样子 ![image](https://user-images.githubusercontent.com/51878592/280909988-4cadb649-5271-4d3a-9acb-e35a9c92c0eb.png)

你更新脚本重新替换一下，应该可以了，页面亮度的锅

**Comment by Crazyboyjw** [comment]
> > > > 有没有支持DSM 7.2-64561这个版本的？ 谢谢
> > > 
> > > 
> > > 已更新
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/51878592/280909690-be677665-2141-4b8c-a693-9ab579d51565.png) 7.2.1使用后 整个系统界面都变得很虚 很多按钮的底色都没了 正常的是下图的样子 ![image](https://user-images.githubusercontent.com/51878592/280909988-4cadb649-5271-4d3a-9acb-e35a9c92c0eb.png)
> 
> > > > 有没有支持DSM 7.2-64561这个版本的？ 谢谢
> > > 
> > > 
> > > 已更新
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/51878592/280909690-be677665-2141-4b8c-a693-9ab579d51565.png) 7.2.1使用后 整个系统界面都变得很虚 很多按钮的底色都没了 正常的是下图的样子 ![image](https://user-images.githubusercontent.com/51878592/280909988-4cadb649-5271-4d3a-9acb-e35a9c92c0eb.png)
> 
> 你更新脚本重新替换一下，应该可以了，页面亮度的锅

感谢  已经可以了
