### ISSUE TITLE
请求分享原始登录页备份文件

### ISSUE THREAD

**Issue by Cyberxxt** [onlypeng/dsm7_login_translucent#4]
大佬好，因为以前通过别人的教程修改了群晖的主页，升级系统后导致现在登录页布局混乱。但已经没有原始的备份文件，运行脚本进行还原也提示错误。

能否请大佬分享群晖的原始登陆页面备份文件用于手动覆盖还原登录页？

感谢

**Comment by onlypeng** [comment]
哪个版本的群晖，修改了哪个文件

**Comment by Cyberxxt** [comment]
> 哪个版本的群晖，修改了哪个文件

修改文件时是DSM7.1，现在升级到了7.2.1
文件应该修改了/usr/syno/synoman/webman/login/目录下的css和dist里的文件

**Comment by onlypeng** [comment]
https://www.123865.com/s/diSbVv-huv2H?提取码:rT3p
你把这两个文件放入/usr/syno/synoman/webman/login/dist/目录，记住先备份，如果/usr/syno/synoman/webman/login/dist/目录有我给你发的这两个文件则先备份，然后再替换我给的这两个。

**Comment by Cyberxxt** [comment]
感谢大佬，替换了文件布局已经修复！、
但是根据以前的操作隔一段时间会恢复成混乱状态（未重启机器）。暂时不知道原因，需要等几天看情况是否复现。

**Comment by Cyberxxt** [comment]
![image](https://github.com/user-attachments/assets/c02ce98c-5553-4cf9-95b6-19e74373d227)

问题复现了：
在文件放到对应目录时界面恢复了。但是等待大约一天后查看目录中的style.css两个文件被自动删除，且界面恢复混乱布局。(系统在过程中未重启）
尝试过修改两个文件的权限为644和755，但是未能解决问题。
想请问是否有可能的解决方法？

**Comment by onlypeng** [comment]
你有添加计划任务或定时任务吗
